### ISSUE TITLE
Using SockJS instead of websockets directly

### ISSUE THREAD

**Issue by salmundani** [tsegismont/vertx-gsoc-2023-qotd#3]
For the _Realtime quotes_ task we have to use websockets. Reading the docs, I'm seeing that it is recommended to use SockJS as it will try to use websockets natively if supported and it fallbacks to AJAX requests if it doesn't support websockets. Should I be using SockJS or should I be using websockets directly? Both implementations' interfaces are pretty much the same anyways

**Comment by tsegismont** [comment]
Please use websockets directly
