### ISSUE TITLE
Incorrect password being used in docker run command

### ISSUE THREAD

**Issue by DenisJulio** [tsegismont/vertx-gsoc-2023-qotd#5]
Hello @tsegismont ,

I tried running the command in the `README.adoc` to run the database:

```bash
docker run \
  -e POSTGRES_USER=quotes \
  -e POSTGRES_PASSWORD=super$ecret \
  -e POSTGRES_DB=quotes \
  -v "$(pwd)/src/main/resources/import.sql":/docker-entrypoint-initdb.d/import.sql \
  -p 5432:5432 \
  -ti \
  postgres:15.2
```
However, I noticed that the password `super$ecret` was not being used for the Postgres instance as intended. The password being stored was `super`. After searching, it seemed the `$` character was being interpreted as part of a shell variable and getting replaced with an empty value.

I found that using single quotes around the password worked as expected:

```bash
docker run \
  -e POSTGRES_USER=quotes \
  -e POSTGRES_PASSWORD='super$ecret' \
  -e POSTGRES_DB=quotes \
  -v "$(pwd)/src/main/resources/import.sql":/docker-entrypoint-initdb.d/import.sql \
  -p 5432:5432 \
  -ti \
  postgres:15.2
```

I thought I would bring this to your attention in case others run into the same issue.

**Comment by tsegismont** [comment]
Thank you @DenisJulio !
